const sampleStudents = [
  {
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    password: "password123",
    accountType: "Student",
    courses: [],
    image: "profile_pic_1.jpg",
    token: "",
    resetPasswordExpires: null,
    courseProgress: [],
    performance: [],
  },
  {
    firstName: "Alice",
    lastName: "Smith",
    email: "alice.smith@example.com",
    password: "password456",
    accountType: "Student",
    courses: [],
    image: "profile_pic_2.jpg",
    token: "",
    resetPasswordExpires: null,
    courseProgress: [],
    performance: [],
  },
  {
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
    password: "password789",
    accountType: "Student",
    courses: [],
    image: "profile_pic_3.jpg",
    token: "",
    resetPasswordExpires: null,
    courseProgress: [],
    performance: [],
  },
  {
    firstName: "Emma",
    lastName: "Wilson",
    email: "emma.wilson@example.com",
    password: "password987",
    accountType: "Student",
    courses: [],
    image: "profile_pic_4.jpg",
    token: "",
    resetPasswordExpires: null,
    courseProgress: [],
    performance: [],
  },
  {
    firstName: "William",
    lastName: "Brown",
    email: "william.brown@example.com",
    password: "password654",
    accountType: "Student",
    courses: [],
    image: "profile_pic_5.jpg",
    token: "",
    resetPasswordExpires: null,
    courseProgress: [],
    performance: [],
  },
  {
    firstName: "Sophia",
    lastName: "Taylor",
    email: "sophia.taylor@example.com",
    password: "password321",
    accountType: "Student",
    courses: [],
    image: "profile_pic_6.jpg",
    token: "",
    resetPasswordExpires: null,
    courseProgress: [],
    performance: [],
  },
  {
    firstName: "Oliver",
    lastName: "Miller",
    email: "oliver.miller@example.com",
    password: "passwordabc",
    accountType: "Student",
    courses: [],
    image: "profile_pic_7.jpg",
    token: "",
    resetPasswordExpires: null,
    courseProgress: [],
    performance: [],
  },
  {
    firstName: "Emily",
    lastName: "Anderson",
    email: "emily.anderson@example.com",
    password: "passworddef",
    accountType: "Student",
    courses: [],
    image: "profile_pic_8.jpg",
    token: "",
    resetPasswordExpires: null,
    courseProgress: [],
    performance: [],
  },
  {
    firstName: "Noah",
    lastName: "Garcia",
    email: "noah.garcia@example.com",
    password: "passwordxyz",
    accountType: "Student",
    courses: [],
    image: "profile_pic_9.jpg",
    token: "",
    resetPasswordExpires: null,
    courseProgress: [],
    performance: [],
  },
  {
    firstName: "Isabella",
    lastName: "Lopez",
    email: "isabella.lopez@example.com",
    password: "passwordmno",
    accountType: "Student",
    courses: [],
    image: "profile_pic_10.jpg",
    token: "",
    resetPasswordExpires: null,
    courseProgress: [],
    performance: [],
  },
];

module.exports = sampleStudents;
