name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build the Docker image
      id: build_image
      run: |
        IMAGE_TAG=somnathmishra01/smart-class-room:$(date +%s)
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: Push the Docker image
      run: docker push ${{ env.IMAGE_TAG }}
